JAVAC  = javac
JAR    = jar
JAR_TXT = customizer.txt
JAR_TARGET = ../CustomizerAvatarJavaCodeGeneration.jar

all:
	javac *.java
	$(JAR) cmf $(JAR_TXT) $(JAR_TARGET) CustomizerAvatarJavaCodeGeneration.class
