/* Generated By:JJTree: Do not edit this line. ASTByteBlacketType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTByteBlacketType extends SimpleNode {
  public ASTByteBlacketType(int id) {
    super(id);
  }

  public ASTByteBlacketType(SimpleCalculatorParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpleCalculatorParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=04bc94705f908d54672981b99d8aa0c5 (do not edit this line) */
