/* Generated By:JJTree: Do not edit this line. ASTByteType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTByteType extends SimpleNode {
  public ASTByteType(int id) {
    super(id);
  }

  public ASTByteType(SimpleCalculatorParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpleCalculatorParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=df368bfb2b369f05dc91eb210ca71181 (do not edit this line) */
