/* Generated By:JJTree: Do not edit this line. ASTConditionRoot.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTConditionRoot extends SimpleNode {
  public ASTConditionRoot(int id) {
    super(id);
  }

  public ASTConditionRoot(SimpleCalculatorParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpleCalculatorParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8d505d06c7e36724edae60b2a2deb164 (do not edit this line) */
