/* Generated By:JJTree: Do not edit this line. ASTCharBlacketType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTCharBlacketType extends SimpleNode {
  public ASTCharBlacketType(int id) {
    super(id);
  }

  public ASTCharBlacketType(SimpleCalculatorParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpleCalculatorParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ed893f78741cce095ad6378289340332 (do not edit this line) */
