/* Generated By:JJTree: Do not edit this line. ASTDoubleType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTDoubleType extends SimpleNode {
  public ASTDoubleType(int id) {
    super(id);
  }

  public ASTDoubleType(SimpleCalculatorParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpleCalculatorParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bdf234bb3a1843c7cfb68046180af25d (do not edit this line) */
