/* Generated By:JJTree: Do not edit this line. ASTFloatType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTFloatType extends SimpleNode {
  public ASTFloatType(int id) {
    super(id);
  }

  public ASTFloatType(SimpleCalculatorParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpleCalculatorParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=12df82e45bc9d7a4469788d9aea894de (do not edit this line) */
