/* Generated By:JJTree: Do not edit this line. ASTFloatBlacketType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTFloatBlacketType extends SimpleNode {
  public ASTFloatBlacketType(int id) {
    super(id);
  }

  public ASTFloatBlacketType(SimpleCalculatorParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpleCalculatorParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7243a7244f88cb15f3c381107cd26334 (do not edit this line) */
