/* Generated By:JJTree: Do not edit this line. ASTIntBlacketType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTIntBlacketType extends SimpleNode {
  public ASTIntBlacketType(int id) {
    super(id);
  }

  public ASTIntBlacketType(SimpleCalculatorParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpleCalculatorParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c60090a1f3fb79a0cc4660264569298d (do not edit this line) */
