/* Generated By:JJTree: Do not edit this line. ASTLongType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTLongType extends SimpleNode {
  public ASTLongType(int id) {
    super(id);
  }

  public ASTLongType(SimpleCalculatorParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpleCalculatorParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0afdbc30a41d2a56aa75b70848f4fae5 (do not edit this line) */
