/* Generated By:JJTree: Do not edit this line. ASTLongBlacketType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTLongBlacketType extends SimpleNode {
  public ASTLongBlacketType(int id) {
    super(id);
  }

  public ASTLongBlacketType(SimpleCalculatorParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpleCalculatorParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b08cb9c0641e25164bbff7f3b45b7ec6 (do not edit this line) */
