/* Generated By:JJTree: Do not edit this line. ASTMethodDeclarationRoot.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTMethodDeclarationRoot extends SimpleNode {
  public ASTMethodDeclarationRoot(int id) {
    super(id);
  }

  public ASTMethodDeclarationRoot(SimpleCalculatorParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpleCalculatorParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8820e6ac64849d8dd83ad4e774f0fd31 (do not edit this line) */
