/* Generated By:JJTree: Do not edit this line. ASTPrimitiveBlacketType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTPrimitiveBlacketType extends SimpleNode {
  public ASTPrimitiveBlacketType(int id) {
    super(id);
  }

  public ASTPrimitiveBlacketType(SimpleCalculatorParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpleCalculatorParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9f1f98dcc0f6b290ce56a8e698cff655 (do not edit this line) */
