/* Generated By:JJTree: Do not edit this line. ASTShortBlacketType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTShortBlacketType extends SimpleNode {
  public ASTShortBlacketType(int id) {
    super(id);
  }

  public ASTShortBlacketType(SimpleCalculatorParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpleCalculatorParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=848cc0ec0541aa94fea0e32611148987 (do not edit this line) */
