/* Generated By:JJTree: Do not edit this line. ASTShortType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTShortType extends SimpleNode {
  public ASTShortType(int id) {
    super(id);
  }

  public ASTShortType(SimpleCalculatorParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpleCalculatorParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=609ce2c5d93698b629ac023f0e038de8 (do not edit this line) */
