/* Generated By:JJTree: Do not edit this line. ASTVoidType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTVoidType extends SimpleNode {
  public ASTVoidType(int id) {
    super(id);
  }

  public ASTVoidType(SimpleCalculatorParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpleCalculatorParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f5d3fba292c9c0ee9cb64765e6305808 (do not edit this line) */
