/* Generated By:JavaCC: Do not edit this line. SimpleCalculatorParserTreeConstants.java Version 4.1d1 */
public interface SimpleCalculatorParserTreeConstants
{
  public int JJTCONDITIONROOT = 0;
  public int JJTEXPR = 1;
  public int JJTCONDITIONALOREXPRESSION = 2;
  public int JJTCONDITIONALANDEXPRESSION = 3;
  public int JJTEQUALITYEXPRESSION = 4;
  public int JJTRELATIONALEXPRESSION = 5;
  public int JJTADDITIVEEXPRESSION = 6;
  public int JJTPRIMARYPREFIX = 7;
  public int JJTLITERAL = 8;
  public int JJTNAME = 9;
  public int JJTINTEGER = 10;
  public int JJTFLOATING = 11;
  public int JJTCHARACTER = 12;
  public int JJTSTRING = 13;
  public int JJTBOOLEANLITERAL = 14;
  public int JJTNULLLITERAL = 15;
  public int JJTMETHODDECLARATIONROOT = 16;
  public int JJTPRIMITIVETYPE = 17;
  public int JJTTYPE = 18;
  public int JJTRESULTTYPE = 19;
  public int JJTVARIABLEDECLARATORID = 20;
  public int JJTFORMALPARAMETER = 21;
  public int JJTFORMALPARAMETERS = 22;
  public int JJTMETHODDECLARATOR = 23;
  public int JJTMETHODDECLARATION = 24;


  public String[] jjtNodeName = {
    "ConditionRoot",
    "Expr",
    "ConditionalOrExpression",
    "ConditionalAndExpression",
    "EqualityExpression",
    "RelationalExpression",
    "AdditiveExpression",
    "PrimaryPrefix",
    "Literal",
    "Name",
    "Integer",
    "Floating",
    "Character",
    "String",
    "BooleanLiteral",
    "NullLiteral",
    "MethodDeclarationRoot",
    "PrimitiveType",
    "Type",
    "ResultType",
    "VariableDeclaratorId",
    "FormalParameter",
    "FormalParameters",
    "MethodDeclarator",
    "MethodDeclaration",
  };
}
/* JavaCC - OriginalChecksum=15d5b068e01ab9a906bf9d123eeb0f71 (do not edit this line) */
