/* Generated By:JavaCC: Do not edit this line. SimpleCalculatorParserTreeConstants.java Version 4.1d1 */
public interface SimpleCalculatorParserTreeConstants
{
  public int JJTCONDITIONROOT = 0;
  public int JJTEXPR = 1;
  public int JJTCONDITIONALOREXPRESSION = 2;
  public int JJTCONDITIONALANDEXPRESSION = 3;
  public int JJTEQUALITYEXPRESSION = 4;
  public int JJTRELATIONALEXPRESSION = 5;
  public int JJTADDITIVEEXPRESSION = 6;
  public int JJTPRIMARYPREFIX = 7;
  public int JJTLITERAL = 8;
  public int JJTNAME = 9;
  public int JJTINTEGER = 10;
  public int JJTFLOATING = 11;
  public int JJTCHARACTER = 12;
  public int JJTSTRING = 13;
  public int JJTBOOLEANLITERAL = 14;
  public int JJTNULLLITERAL = 15;
  public int JJTMETHODDECLARATIONROOT = 16;
  public int JJTPRIMITIVETYPE = 17;
  public int JJTPRIMITIVEBLACKETTYPE = 18;
  public int JJTBOOLEANBLACKETTYPE = 19;
  public int JJTCHARBLACKETTYPE = 20;
  public int JJTBYTEBLACKETTYPE = 21;
  public int JJTSHORTBLACKETTYPE = 22;
  public int JJTINTBLACKETTYPE = 23;
  public int JJTLONGBLACKETTYPE = 24;
  public int JJTFLOATBLACKETTYPE = 25;
  public int JJTDOUBLEBLACKETTYPE = 26;
  public int JJTBOOLEANTYPE = 27;
  public int JJTCHARTYPE = 28;
  public int JJTBYTETYPE = 29;
  public int JJTSHORTTYPE = 30;
  public int JJTINTTYPE = 31;
  public int JJTLONGTYPE = 32;
  public int JJTFLOATTYPE = 33;
  public int JJTDOUBLETYPE = 34;
  public int JJTTYPE = 35;
  public int JJTVOIDTYPE = 36;
  public int JJTRESULTTYPE = 37;
  public int JJTARRAYBRACKETS = 38;
  public int JJTVARIABLEDECLARATORID = 39;
  public int JJTFORMALPARAMETER = 40;
  public int JJTFORMALPARAMETERS = 41;
  public int JJTMETHODDECLARATOR = 42;
  public int JJTMETHODDECLARATION = 43;


  public String[] jjtNodeName = {
    "ConditionRoot",
    "Expr",
    "ConditionalOrExpression",
    "ConditionalAndExpression",
    "EqualityExpression",
    "RelationalExpression",
    "AdditiveExpression",
    "PrimaryPrefix",
    "Literal",
    "Name",
    "Integer",
    "Floating",
    "Character",
    "String",
    "BooleanLiteral",
    "NullLiteral",
    "MethodDeclarationRoot",
    "PrimitiveType",
    "PrimitiveBlacketType",
    "BooleanBlacketType",
    "CharBlacketType",
    "ByteBlacketType",
    "ShortBlacketType",
    "IntBlacketType",
    "LongBlacketType",
    "FloatBlacketType",
    "DoubleBlacketType",
    "BooleanType",
    "CharType",
    "ByteType",
    "ShortType",
    "IntType",
    "LongType",
    "FloatType",
    "DoubleType",
    "Type",
    "VoidType",
    "ResultType",
    "ArrayBrackets",
    "VariableDeclaratorId",
    "FormalParameter",
    "FormalParameters",
    "MethodDeclarator",
    "MethodDeclaration",
  };
}
/* JavaCC - OriginalChecksum=8c2b6b8df0c33e685ffaf74223cc0e9f (do not edit this line) */
