/* Generated By:JavaCC: Do not edit this line. SimpleCalculatorParserTreeConstants.java Version 4.1d1 */
public interface SimpleCalculatorParserTreeConstants
{
  public int JJTCONDITIONROOT = 0;
  public int JJTEXPR = 1;
  public int JJTCONDITIONALOREXPRESSION = 2;
  public int JJTCONDITIONALANDEXPRESSION = 3;
  public int JJTEQUALITYEXPRESSION = 4;
  public int JJTRELATIONALEXPRESSION = 5;
  public int JJTADDITIVEEXPRESSION = 6;
  public int JJTPRIMARYPREFIX = 7;
  public int JJTLITERAL = 8;
  public int JJTNAME = 9;
  public int JJTINTEGER = 10;
  public int JJTFLOATING = 11;
  public int JJTCHARACTER = 12;
  public int JJTSTRING = 13;
  public int JJTBOOLEANLITERAL = 14;
  public int JJTNULLLITERAL = 15;
  public int JJTMETHODDECLARATIONROOT = 16;
  public int JJTPRIMITIVETYPE = 17;
  public int JJTBOOLEANTYPE = 18;
  public int JJTCHARTYPE = 19;
  public int JJTBYTETYPE = 20;
  public int JJTSHORTTYPE = 21;
  public int JJTINTTYPE = 22;
  public int JJTLONGTYPE = 23;
  public int JJTFLOATTYPE = 24;
  public int JJTDOUBLETYPE = 25;
  public int JJTTYPE = 26;
  public int JJTVOIDTYPE = 27;
  public int JJTRESULTTYPE = 28;
  public int JJTARRAYBRACKETS = 29;
  public int JJTVARIABLEDECLARATORID = 30;
  public int JJTFORMALPARAMETER = 31;
  public int JJTFORMALPARAMETERS = 32;
  public int JJTMETHODDECLARATOR = 33;
  public int JJTMETHODDECLARATION = 34;


  public String[] jjtNodeName = {
    "ConditionRoot",
    "Expr",
    "ConditionalOrExpression",
    "ConditionalAndExpression",
    "EqualityExpression",
    "RelationalExpression",
    "AdditiveExpression",
    "PrimaryPrefix",
    "Literal",
    "Name",
    "Integer",
    "Floating",
    "Character",
    "String",
    "BooleanLiteral",
    "NullLiteral",
    "MethodDeclarationRoot",
    "PrimitiveType",
    "BooleanType",
    "CharType",
    "ByteType",
    "ShortType",
    "IntType",
    "LongType",
    "FloatType",
    "DoubleType",
    "Type",
    "VoidType",
    "ResultType",
    "ArrayBrackets",
    "VariableDeclaratorId",
    "FormalParameter",
    "FormalParameters",
    "MethodDeclarator",
    "MethodDeclaration",
  };
}
/* JavaCC - OriginalChecksum=29a1efdae5239023d6c8dccb552133d4 (do not edit this line) */
