/* Generated By:JavaCC: Do not edit this line. SimpleCalculatorParserVisitor.java Version 4.1d1 */
public interface SimpleCalculatorParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTConditionRoot node, Object data);
  public Object visit(ASTExpr node, Object data);
  public Object visit(ASTConditionalOrExpression node, Object data);
  public Object visit(ASTConditionalAndExpression node, Object data);
  public Object visit(ASTEqualityExpression node, Object data);
  public Object visit(ASTRelationalExpression node, Object data);
  public Object visit(ASTAdditiveExpression node, Object data);
  public Object visit(ASTPrimaryPrefix node, Object data);
  public Object visit(ASTLiteral node, Object data);
  public Object visit(ASTName node, Object data);
  public Object visit(ASTInteger node, Object data);
  public Object visit(ASTFloating node, Object data);
  public Object visit(ASTCharacter node, Object data);
  public Object visit(ASTString node, Object data);
  public Object visit(ASTBooleanLiteral node, Object data);
  public Object visit(ASTNullLiteral node, Object data);
  public Object visit(ASTMethodDeclarationRoot node, Object data);
  public Object visit(ASTPrimitiveType node, Object data);
  public Object visit(ASTType node, Object data);
  public Object visit(ASTResultType node, Object data);
  public Object visit(ASTVariableDeclaratorId node, Object data);
  public Object visit(ASTFormalParameter node, Object data);
  public Object visit(ASTFormalParameters node, Object data);
  public Object visit(ASTMethodDeclarator node, Object data);
  public Object visit(ASTMethodDeclaration node, Object data);
}
/* JavaCC - OriginalChecksum=8bead6e0685fd4c2a96f5d2bb3c8fe0e (do not edit this line) */
