
DIR_CFLAGS = -D_HEXO_INTTYPES_DEPRECATED

objs = \
	vfs.o \
	helpers.o \
	globals.o \
	file.o \
	node.o \
	fs.o

doc_headers = vfs/file.h vfs/fs.h vfs/globals.h vfs/helpers.h	\
vfs/defs.h vfs/ops.h vfs/types.h vfs/vfs.h

subdirs = fs

#DIR_CFLAGS=-O0 -ggdb
#vfs.o_CFLAGS=-O0 -ggdb
