/* Generated By:JJTree: Do not edit this line. ASTFloating.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTFloating extends SimpleNode {
  public ASTFloating(int id) {
    super(id);
  }

  public ASTFloating(SimpleCalculatorParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpleCalculatorParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=470db9bf3f9b222f91aebb74369f490d (do not edit this line) */
