/* Generated By:JavaCC: Do not edit this line. SimpleCalculatorParserTreeConstants.java Version 4.1d1 */
public interface SimpleCalculatorParserTreeConstants
{
  public int JJTEXPR = 0;
  public int JJTCONDITIONALOREXPRESSION = 1;
  public int JJTCONDITIONALANDEXPRESSION = 2;
  public int JJTEQUALITYEXPRESSION = 3;
  public int JJTRELATIONALEXPRESSION = 4;
  public int JJTPRIMARYPREFIX = 5;
  public int JJTLITERAL = 6;
  public int JJTNAME = 7;
  public int JJTINTEGER = 8;
  public int JJTFLOATING = 9;
  public int JJTCHARACTER = 10;
  public int JJTSTRING = 11;
  public int JJTBOOLEANLITERAL = 12;
  public int JJTNULLLITERAL = 13;


  public String[] jjtNodeName = {
    "Expr",
    "ConditionalOrExpression",
    "ConditionalAndExpression",
    "EqualityExpression",
    "RelationalExpression",
    "PrimaryPrefix",
    "Literal",
    "Name",
    "Integer",
    "Floating",
    "Character",
    "String",
    "BooleanLiteral",
    "NullLiteral",
  };
}
/* JavaCC - OriginalChecksum=3caadc7b7be7ca0113d1dec67ba5e2b9 (do not edit this line) */
