/* Generated By:JavaCC: Do not edit this line. SimpleCalculatorParserTreeConstants.java Version 4.1d1 */
public interface SimpleCalculatorParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTEXPR = 1;
  public int JJTCONDITIONALOREXPRESSION = 2;
  public int JJTCONDITIONALANDEXPRESSION = 3;
  public int JJTEQUALITYEXPRESSION = 4;
  public int JJTRELATIONALEXPRESSION = 5;
  public int JJTADDITIVEEXPRESSION = 6;
  public int JJTPRIMARYPREFIX = 7;
  public int JJTLITERAL = 8;
  public int JJTNAME = 9;
  public int JJTINTEGER = 10;
  public int JJTFLOATING = 11;
  public int JJTCHARACTER = 12;
  public int JJTSTRING = 13;
  public int JJTBOOLEANLITERAL = 14;
  public int JJTNULLLITERAL = 15;


  public String[] jjtNodeName = {
    "Root",
    "Expr",
    "ConditionalOrExpression",
    "ConditionalAndExpression",
    "EqualityExpression",
    "RelationalExpression",
    "AdditiveExpression",
    "PrimaryPrefix",
    "Literal",
    "Name",
    "Integer",
    "Floating",
    "Character",
    "String",
    "BooleanLiteral",
    "NullLiteral",
  };
}
/* JavaCC - OriginalChecksum=c2d70a4b2904bbe9c510cc992b2c48de (do not edit this line) */
