#ifndef MAIN_H
#define MAIN_H
extern pthread_mutex_t __mainMutex;

/* Synchronous channels */
extern syncchannel __DSRSC_Management_broadcastEmergencyBrakingMessage__DangerAvoidanceStrategy_forwardEmergency;
extern syncchannel __NeighbourhoodTableManagement_sendTable__PlausibilityCheck_getNodeList;
extern syncchannel __DangerAvoidanceStrategy_brakePower__BrakeManagement_brake;
extern syncchannel __DangerAvoidanceStrategy_brake__PlausibilityCheck_brake;
extern syncchannel __PlausibilityCheck_getInfoOnSpeed__VehiculeDynamicsManagement_getInfoOnSpeed;
extern syncchannel __SpeedSensor_updateOnSpeed__VehiculeDynamicsManagement_updateOnSpeed;
extern syncchannel __PlausibilityCheck_getInfoOnObstacle__ObjectListManagement_getInfoOnObstacle;
extern syncchannel __RadarSensor_obstacleAhead__ObjectListManagement_isObstacleAhead;
extern syncchannel __CorrectnessChecking_toPlausibityCheckMessage__PlausibilityCheck_getEmergencyMessageToVerify;
extern syncchannel __DSRSC_Management_forwardEmergencyBrakingMessage__CorrectnessChecking_getEmergencyBrakingMessage;
extern syncchannel __DSRSC_Management_setCarPosition__NeighbourhoodTableManagement_addANode;
extern syncchannel __CarPositionSimulator_carPosition__DSRSC_Management_carPosition;
extern syncchannel __EmergencySimulator_obstacleDetected__DSRSC_Management_obstacleDetected;
extern syncchannel __GPSSensor_setPosition__NeighbourhoodTableManagement_setPosition;
/* Asynchronous channels */
extern asyncchannel __DangerAvoidanceStrategy_reducePower__DrivingPowerReductionStrategy_getReducePowerOrder;
#endif
