#ifndef MAIN_H
#define MAIN_H
extern pthread_mutex_t __mainMutex;

/* Synchronous channels */
/* Asynchronous channels */
extern asyncchannel __DSRSC_Management_broadcastEmergencyBrakingMessage__DangerAvoidanceStrategy_forwardEmergency;
extern asyncchannel __NeighbourhoodTableManagement_sendTable__PlausibilityCheck_getNodeList;
extern asyncchannel __DangerAvoidanceStrategy_reducePower__DrivingPowerReductionStrategy_getReducePowerOrder;
extern asyncchannel __DangerAvoidanceStrategy_brakePower__BrakeManagement_brake;
extern asyncchannel __DangerAvoidanceStrategy_brake__PlausibilityCheck_brake;
extern asyncchannel __PlausibilityCheck_getInfoOnSpeed__VehiculeDynamicsManagement_getInfoOnSpeed;
extern asyncchannel __SpeedSensor_updateOnSpeed__VehiculeDynamicsManagement_updateOnSpeed;
extern asyncchannel __PlausibilityCheck_getInfoOnObstacle__ObjectListManagement_getInfoOnObstacle;
extern asyncchannel __RadarSensor_obstacleAhead__ObjectListManagement_isObstacleAhead;
extern asyncchannel __CorrectnessChecking_toPlausibityCheckMessage__PlausibilityCheck_getEmergencyMessageToVerify;
extern asyncchannel __DSRSC_Management_forwardEmergencyBrakingMessage__CorrectnessChecking_getEmergencyBrakingMessage;
extern asyncchannel __DSRSC_Management_setCarPosition__NeighbourhoodTableManagement_addANode;
extern asyncchannel __CarPositionSimulator_carPosition__DSRSC_Management_carPosition;
extern asyncchannel __EmergencySimulator_obstacleDetected__DSRSC_Management_obstacleDetected;
extern asyncchannel __GPSSensor_setPosition__NeighbourhoodTableManagement_setPosition;
#endif
