
ifeq ($(CONFIG_DRIVER_TIMER_8253), defined)
subdirs += 8253
endif

ifeq ($(CONFIG_DRIVER_TIMER_EMU), defined)
subdirs += emu
endif

ifeq ($(CONFIG_DRIVER_TIMER_SOCLIB), defined)
subdirs += soclib
endif

ifeq ($(CONFIG_DRIVER_TIMER_PITC_6079A), defined)
subdirs += pitc_6079a
endif

