/* Copyright or (C) 2017-2020 Nokia
 * Copyright or (C) GET / ENST, Telecom-Paris
 * Licensed under the BSD 3 Clause license
 * SPDX-License-Identifier: BSD-3-Clause
 */


package tmltranslator.dsez3engine;

import tmltranslator.*;

import java.util.ArrayList;
import java.util.List;

/**
 * Class OptimizationResult
 * Object for manipulating results generated by Z3
 * Creation: 26/02/2019
 *
 * @author Ludovic APVRILLE
 * @version 1.0 27/02/2019
 */

public class OptimizationResult {

   public String result = "";
   public boolean mappingFound = false;
   public String error = null;
   public TMLMapping resultingMapping;

    public OptimizationResult() {
    }

    public boolean hasError() {
        return error != null;
    }

    public boolean mappingfound() {
        return mappingFound;
    }


}
