
ifeq ($(CONFIG_DRIVER_SPI), defined)
#objs += device_spi.o
endif

ifeq ($(CONFIG_DRIVER_SPI_SPI6088D), defined)
 subdirs += spi6088d
endif

ifeq ($(CONFIG_DRIVER_SPI_OPENCORES), defined)
 subdirs += oc_spi_controller
endif
