SOCLIB_CPU=ppc
MUTEKH_CPU=ppc

PATH+=/opt/mutekh/bin
export PATH

updateruntime:
	cp ~/TTool/executablecode/src/*.c ~/TTool/MPSoC/mutekh/libavatar/
	cp ~/TTool/executablecode/src/*.h ~/TTool/MPSoC/mutekh/libavatar/include/  

updategeneratedcode:
	cp ~/TTool/executablecode/generated_src/*.h ~/TTool/MPSoC/mutekh/examples/avatar
	cp ~/TTool/executablecode/generated_src/*.c ~/TTool/MPSoC/mutekh/examples/avatar	
	cp ~/TTool/executablecode/Makefile.soclib ~/TTool/MPSoC/mutekh/examples/avatar/Makefile

compilesoclib:
	cd ~/TTool/MPSoC/mutekh; make CONF=examples/avatar/config BUILD=soclib-$(MUTEKH_CPU):pf-tutorial

runsoclib:
	echo "running soclib"
	cd ~/TTool/MPSoC/soclib/soclib/platform/topcells/caba-vgmn-mutekh_kernel_tutorial; SOCLIB_GDB=S ./system.x $(SOCLIB_CPU):$(SOCLIB_CPU_COUNT) ~/TTool/MPSoC/mutekh/avatar-soclib-$(MUTEKH_CPU).out
allsoclib: updateruntime updategeneratedcode compilesoclib runsoclib

