
#if defined(DEPLOY_RAM0_NAME)
	DEPLOY_RAM0_NAME (RWAL) : ORIGIN = DEPLOY_RAM0_ADDR, LENGTH = DEPLOY_RAM0_SIZE
#endif
#if defined(CACHED_RAM0_NAME)
	CACHED_RAM0_NAME (RWAL) : ORIGIN = CACHED_RAM0_ADDR, LENGTH = CACHED_RAM0_SIZE
#endif
#if defined(DEPLOY_RAM1_NAME)
	DEPLOY_RAM1_NAME (RWAL) : ORIGIN = DEPLOY_RAM1_ADDR, LENGTH = DEPLOY_RAM1_SIZE
#endif
#if defined(CACHED_RAM1_NAME)
	CACHED_RAM1_NAME (RWAL) : ORIGIN = CACHED_RAM1_ADDR, LENGTH = CACHED_RAM1_SIZE
#endif
#if defined(DEPLOY_RAM2_NAME)
	DEPLOY_RAM2_NAME (RWAL) : ORIGIN = DEPLOY_RAM2_ADDR, LENGTH = DEPLOY_RAM2_SIZE
#endif
#if defined(CACHED_RAM2_NAME)
	CACHED_RAM2_NAME (RWAL) : ORIGIN = CACHED_RAM2_ADDR, LENGTH = CACHED_RAM2_SIZE
#endif
#if defined(DEPLOY_RAM3_NAME)
	DEPLOY_RAM3_NAME (RWAL) : ORIGIN = DEPLOY_RAM3_ADDR, LENGTH = DEPLOY_RAM3_SIZE
#endif
#if defined(CACHED_RAM3_NAME)
	CACHED_RAM3_NAME (RWAL) : ORIGIN = CACHED_RAM3_ADDR, LENGTH = CACHED_RAM3_SIZE
#endif
#if defined(DEPLOY_RAM4_NAME)
	DEPLOY_RAM4_NAME (RWAL) : ORIGIN = DEPLOY_RAM4_ADDR, LENGTH = DEPLOY_RAM4_SIZE
#endif
#if defined(CACHED_RAM4_NAME)
	CACHED_RAM4_NAME (RWAL) : ORIGIN = CACHED_RAM4_ADDR, LENGTH = CACHED_RAM4_SIZE
#endif
#if defined(DEPLOY_RAM5_NAME)
	DEPLOY_RAM5_NAME (RWAL) : ORIGIN = DEPLOY_RAM5_ADDR, LENGTH = DEPLOY_RAM5_SIZE
#endif
#if defined(CACHED_RAM5_NAME)
	CACHED_RAM5_NAME (RWAL) : ORIGIN = CACHED_RAM5_ADDR, LENGTH = CACHED_RAM5_SIZE
#endif
#if defined(DEPLOY_RAM6_NAME)
	DEPLOY_RAM6_NAME (RWAL) : ORIGIN = DEPLOY_RAM6_ADDR, LENGTH = DEPLOY_RAM6_SIZE
#endif
#if defined(CACHED_RAM6_NAME)
	CACHED_RAM6_NAME (RWAL) : ORIGIN = CACHED_RAM6_ADDR, LENGTH = CACHED_RAM6_SIZE
#endif
#if defined(DEPLOY_RAM7_NAME)
	DEPLOY_RAM7_NAME (RWAL) : ORIGIN = DEPLOY_RAM7_ADDR, LENGTH = DEPLOY_RAM7_SIZE
#endif
#if defined(CACHED_RAM7_NAME)
	CACHED_RAM7_NAME (RWAL) : ORIGIN = CACHED_RAM7_ADDR, LENGTH = CACHED_RAM7_SIZE
#endif
#if defined(DEPLOY_RAM8_NAME)
	DEPLOY_RAM8_NAME (RWAL) : ORIGIN = DEPLOY_RAM8_ADDR, LENGTH = DEPLOY_RAM8_SIZE
#endif
#if defined(CACHED_RAM8_NAME)
	CACHED_RAM8_NAME (RWAL) : ORIGIN = CACHED_RAM8_ADDR, LENGTH = CACHED_RAM8_SIZE
#endif
#if defined(DEPLOY_RAM9_NAME)
	DEPLOY_RAM9_NAME (RWAL) : ORIGIN = DEPLOY_RAM9_ADDR, LENGTH = DEPLOY_RAM9_SIZE
#endif
#if defined(CACHED_RAM9_NAME)
	CACHED_RAM9_NAME (RWAL) : ORIGIN = CACHED_RAM9_ADDR, LENGTH = CACHED_RAM9_SIZE
#endif
#if defined(DEPLOY_RAM10_NAME)
	DEPLOY_RAM10_NAME (RWAL) : ORIGIN = DEPLOY_RAM10_ADDR, LENGTH = DEPLOY_RAM10_SIZE
#endif
#if defined(CACHED_RAM10_NAME)
	CACHED_RAM10_NAME (RWAL) : ORIGIN = CACHED_RAM10_ADDR, LENGTH = CACHED_RAM10_SIZE
#endif
#if defined(DEPLOY_RAM11_NAME)
	DEPLOY_RAM11_NAME (RWAL) : ORIGIN = DEPLOY_RAM11_ADDR, LENGTH = DEPLOY_RAM11_SIZE
#endif
#if defined(CACHED_RAM11_NAME)
	CACHED_RAM11_NAME (RWAL) : ORIGIN = CACHED_RAM11_ADDR, LENGTH = CACHED_RAM11_SIZE
#endif
#if defined(DEPLOY_RAM12_NAME)
	DEPLOY_RAM12_NAME (RWAL) : ORIGIN = DEPLOY_RAM12_ADDR, LENGTH = DEPLOY_RAM12_SIZE
#endif
#if defined(CACHED_RAM12_NAME)
	CACHED_RAM12_NAME (RWAL) : ORIGIN = CACHED_RAM12_ADDR, LENGTH = CACHED_RAM12_SIZE
#endif
#if defined(DEPLOY_RAM13_NAME)
	DEPLOY_RAM13_NAME (RWAL) : ORIGIN = DEPLOY_RAM13_ADDR, LENGTH = DEPLOY_RAM13_SIZE
#endif
#if defined(CACHED_RAM13_NAME)
	CACHED_RAM13_NAME (RWAL) : ORIGIN = CACHED_RAM13_ADDR, LENGTH = CACHED_RAM13_SIZE
#endif
#if defined(DEPLOY_RAM14_NAME)
	DEPLOY_RAM14_NAME (RWAL) : ORIGIN = DEPLOY_RAM14_ADDR, LENGTH = DEPLOY_RAM14_SIZE
#endif
#if defined(CACHED_RAM14_NAME)
	CACHED_RAM14_NAME (RWAL) : ORIGIN = CACHED_RAM14_ADDR, LENGTH = CACHED_RAM14_SIZE
#endif
#if defined(DEPLOY_RAM15_NAME)
	DEPLOY_RAM15_NAME (RWAL) : ORIGIN = DEPLOY_RAM15_ADDR, LENGTH = DEPLOY_RAM15_SIZE
#endif
#if defined(CACHED_RAM15_NAME)
	CACHED_RAM15_NAME (RWAL) : ORIGIN = CACHED_RAM15_ADDR, LENGTH = CACHED_RAM15_SIZE
#endif
#if defined(DEPLOY_RAM16_NAME)
	DEPLOY_RAM16_NAME (RWAL) : ORIGIN = DEPLOY_RAM16_ADDR, LENGTH = DEPLOY_RAM16_SIZE
#endif
#if defined(CACHED_RAM16_NAME)
	CACHED_RAM16_NAME (RWAL) : ORIGIN = CACHED_RAM16_ADDR, LENGTH = CACHED_RAM16_SIZE
#endif
#if defined(DEPLOY_RAM17_NAME)
	DEPLOY_RAM17_NAME (RWAL) : ORIGIN = DEPLOY_RAM17_ADDR, LENGTH = DEPLOY_RAM17_SIZE
#endif
#if defined(CACHED_RAM17_NAME)
	CACHED_RAM17_NAME (RWAL) : ORIGIN = CACHED_RAM17_ADDR, LENGTH = CACHED_RAM17_SIZE
#endif
#if defined(DEPLOY_RAM18_NAME)
	DEPLOY_RAM18_NAME (RWAL) : ORIGIN = DEPLOY_RAM18_ADDR, LENGTH = DEPLOY_RAM18_SIZE
#endif
#if defined(CACHED_RAM18_NAME)
	CACHED_RAM18_NAME (RWAL) : ORIGIN = CACHED_RAM18_ADDR, LENGTH = CACHED_RAM18_SIZE
#endif
#if defined(DEPLOY_RAM19_NAME)
	DEPLOY_RAM19_NAME (RWAL) : ORIGIN = DEPLOY_RAM19_ADDR, LENGTH = DEPLOY_RAM19_SIZE
#endif
#if defined(CACHED_RAM19_NAME)
	CACHED_RAM19_NAME (RWAL) : ORIGIN = CACHED_RAM19_ADDR, LENGTH = CACHED_RAM19_SIZE
#endif
#if defined(DEPLOY_RAM20_NAME)
	DEPLOY_RAM20_NAME (RWAL) : ORIGIN = DEPLOY_RAM20_ADDR, LENGTH = DEPLOY_RAM20_SIZE
#endif
#if defined(CACHED_RAM20_NAME)
	CACHED_RAM20_NAME (RWAL) : ORIGIN = CACHED_RAM20_ADDR, LENGTH = CACHED_RAM20_SIZE
#endif
#if defined(DEPLOY_RAM21_NAME)
	DEPLOY_RAM21_NAME (RWAL) : ORIGIN = DEPLOY_RAM21_ADDR, LENGTH = DEPLOY_RAM21_SIZE
#endif
#if defined(CACHED_RAM21_NAME)
	CACHED_RAM21_NAME (RWAL) : ORIGIN = CACHED_RAM21_ADDR, LENGTH = CACHED_RAM21_SIZE
#endif
#if defined(DEPLOY_RAM22_NAME)
	DEPLOY_RAM22_NAME (RWAL) : ORIGIN = DEPLOY_RAM22_ADDR, LENGTH = DEPLOY_RAM22_SIZE
#endif
#if defined(CACHED_RAM22_NAME)
	CACHED_RAM22_NAME (RWAL) : ORIGIN = CACHED_RAM22_ADDR, LENGTH = CACHED_RAM22_SIZE
#endif
#if defined(DEPLOY_RAM23_NAME)
	DEPLOY_RAM23_NAME (RWAL) : ORIGIN = DEPLOY_RAM23_ADDR, LENGTH = DEPLOY_RAM23_SIZE
#endif
#if defined(CACHED_RAM23_NAME)
	CACHED_RAM23_NAME (RWAL) : ORIGIN = CACHED_RAM23_ADDR, LENGTH = CACHED_RAM23_SIZE
#endif
#if defined(DEPLOY_RAM24_NAME)
	DEPLOY_RAM24_NAME (RWAL) : ORIGIN = DEPLOY_RAM24_ADDR, LENGTH = DEPLOY_RAM24_SIZE
#endif
#if defined(CACHED_RAM24_NAME)
	CACHED_RAM24_NAME (RWAL) : ORIGIN = CACHED_RAM24_ADDR, LENGTH = CACHED_RAM24_SIZE
#endif
#if defined(DEPLOY_RAM25_NAME)
	DEPLOY_RAM25_NAME (RWAL) : ORIGIN = DEPLOY_RAM25_ADDR, LENGTH = DEPLOY_RAM25_SIZE
#endif
#if defined(CACHED_RAM25_NAME)
	CACHED_RAM25_NAME (RWAL) : ORIGIN = CACHED_RAM25_ADDR, LENGTH = CACHED_RAM25_SIZE
#endif
#if defined(DEPLOY_RAM26_NAME)
	DEPLOY_RAM26_NAME (RWAL) : ORIGIN = DEPLOY_RAM26_ADDR, LENGTH = DEPLOY_RAM26_SIZE
#endif
#if defined(CACHED_RAM26_NAME)
	CACHED_RAM26_NAME (RWAL) : ORIGIN = CACHED_RAM26_ADDR, LENGTH = CACHED_RAM26_SIZE
#endif
#if defined(DEPLOY_RAM27_NAME)
	DEPLOY_RAM27_NAME (RWAL) : ORIGIN = DEPLOY_RAM27_ADDR, LENGTH = DEPLOY_RAM27_SIZE
#endif
#if defined(CACHED_RAM27_NAME)
	CACHED_RAM27_NAME (RWAL) : ORIGIN = CACHED_RAM27_ADDR, LENGTH = CACHED_RAM27_SIZE
#endif
#if defined(DEPLOY_RAM28_NAME)
	DEPLOY_RAM28_NAME (RWAL) : ORIGIN = DEPLOY_RAM28_ADDR, LENGTH = DEPLOY_RAM28_SIZE
#endif
#if defined(CACHED_RAM28_NAME)
	CACHED_RAM28_NAME (RWAL) : ORIGIN = CACHED_RAM28_ADDR, LENGTH = CACHED_RAM28_SIZE
#endif
