JAVAC  = javac
JAR    = jar
JAR_TXT = customizer.txt
JAR_TARGET = ../CustomizerGraphicalComponent.jar

all:
	javac *.java
	$(JAR) cmf $(JAR_TXT) $(JAR_TARGET) CustomizerGraphicalComponent.class myicon.gif
