/**Copyright or (C) or Copr. GET / ENST, Telecom-Paris, Ludovic Apvrille
 *
 * ludovic.apvrille AT enst.fr
 *
 * This software is a computer program whose purpose is to allow the
 * edition of TURTLE analysis, design and deployment diagrams, to
 * allow the generation of RT-LOTOS or Java code from this diagram,
 * and at last to allow the analysis of formal validation traces
 * obtained from external tools, e.g. RTL from LAAS-CNRS and CADP
 * from INRIA Rhone-Alpes.
 *
 * This software is governed by the CeCILL  license under French law and
 * abiding by the rules of distribution of free software.  You can  use,
 * modify and/ or redistribute the software under the terms of the CeCILL
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and  rights to copy,
 * modify and redistribute granted by the license, users are provided only
 * with a limited warranty  and the software's author,  the holder of the
 * economic rights,  and the successive licensors  have only  limited
 * liability.
 *
 * In this respect, the user's attention is drawn to the risks associated
 * with loading,  using,  modifying and/or developing or reproducing the
 * software by the user in light of its specific status of free software,
 * that may mean  that it is complicated to manipulate,  and  that  also
 * therefore means  that it is reserved for developers  and  experienced
 * professionals having in-depth computer knowledge. Users are therefore
 * encouraged to load and test the software's suitability as regards their
 * requirements in conditions enabling the security of their systems and/or
 * data to be ensured and,  more generally, to use and operate it in the
 * same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 *
 * /**
 * Class DocumentationGenerator
 * Generation of documentation from TTool diagrams
 * Creation: 19/09/2008
 * @version 1.0 19/09/2008
 * @author Ludovic APVRILLE
 * @see
 */


package ui;

import javax.swing.*;
import java.util.*;
import java.io.*;
import java.awt.image.*;
import javax.imageio.*;

import myutil.*;

public class DocumentationGenerator {
    
    // type
    private Vector panels; // TURTLEPanels
	private JTabbedPane mainTabbedPane;
	private int firstHeadingNumber = 1;
	private String title = "TTTool project";
	private String fileName = "doc.html";
	private String path;
	
	private String doc;
	
    
    public DocumentationGenerator(Vector _panels, JTabbedPane _mainTabbedPane, String _path) {
		panels = _panels;
		mainTabbedPane = _mainTabbedPane;
		path = _path + "/";
    }
	
	public void setFirstHeadingNumber(int _firstHeadingNumber) {
		firstHeadingNumber = _firstHeadingNumber;
	}
	
	public String getDocumentation() {
		return doc;
	}
	
	public void setTitle(String _title) {
		title = _title;
	}
	
	public String getTitle() {
		return title;
	}
	
	public boolean generateDocumentation() {
		int i, j;
		BufferedImage image;
		TURTLEPanel tp;
		TDiagramPanel tdp;
		File file1;
		
		doc = "";
		doc += "<html>\n";
		doc += getDocumentationHeader();
		doc += "<body>\n";
		
		for(i=0; i<panels.size(); i++) {
			tp = (TURTLEPanel)(panels.elementAt(i));
			doc += "<h" + firstHeadingNumber + ">" + mainTabbedPane.getTitleAt(i) + "</h" + firstHeadingNumber + ">\n";
			for(j=0; j<tp.panels.size(); j++) {
				tdp = (TDiagramPanel)(tp.panels.elementAt(j));
				doc += "<h" + (firstHeadingNumber+1) + ">" + tp.tabbedPane.getTitleAt(j) + "</h" + (firstHeadingNumber+1) + ">\n";
				image = tdp.performMinimalCapture();
				file1 = new File(path + "img_" + i + "_" + j + ".png");
				//frame.paint(frame.getGraphics());
				try {
					// save captured image to PNG file
					ImageIO.write(image, "png", file1);
					doc += "<img src=\"img_" + i + "_" + j + "\" align=center>\n";
				} catch (Exception e) {
					System.out.println("Image (" + i + ", " + j + ") could not be captured");
				}
			}
		}
		
		doc+="</body>\n</html>";
		
		try {
			FileUtils.saveFile(path+fileName, doc);
		} catch (FileException fe) {
			System.out.println("HTML file couldnot be saved");
			return false;
		}
		
		return true;
	}
	
	public String getDocumentationHeader() {
		String tmpdoc="";
		tmpdoc += "<!----- Automatically generated by TTool ";
		tmpdoc += DefaultText.getFullVersion();
		tmpdoc += "---->\n";
		tmpdoc += "\n<head>\n<title>";
		tmpdoc += getTitle();
		tmpdoc += "</title>\n</head>\n";
		return tmpdoc;
	}
    
   
}