#ifndef MAIN_H
#define MAIN_H
extern pthread_mutex_t __mainMutex;

/* Synchronous channels */
extern syncchannel __TCPIP_timeoutPacket__TCPPacketManager_timeoutPacket;
extern syncchannel __TCPIP_emptyListOfPackets__TCPPacketManager_empty;
extern syncchannel __TCPIP_addPacket__TCPPacketManager_addPacket;
extern syncchannel __TCPIP_ackPacket__TCPPacketManager_ackPacket;
extern syncchannel __Application_open__TCPIP_open;
extern syncchannel __Application_close__TCPIP_close;
extern syncchannel __Application_abort__TCPIP_abort;
extern syncchannel __Application_sendTCP__TCPIP_send_TCP;
extern syncchannel __SmartCardController_fromTtoP__TCPIP_fromTtoP;
extern syncchannel __SmartCardController_fromPtoT__TCPIP_fromPtoT;
extern syncchannel __SmartCardController_start_TCPIP__TCPIP_start;
extern syncchannel __SmartCardController_reset__InterfaceDevice_reset;
extern syncchannel __SmartCardController_pTS__InterfaceDevice_pTS;
extern syncchannel __SmartCardController_dataReady__InterfaceDevice_data_Ready;
extern syncchannel __SmartCardController_activation__InterfaceDevice_activation;
extern syncchannel __SmartCardController_fromDtoSC__InterfaceDevice_fromDtoSC;
extern syncchannel __SmartCardController_answerToReset__InterfaceDevice_answerToReset;
extern syncchannel __SmartCardController_pTSCConfirm__InterfaceDevice_pTSConfirm;
extern syncchannel __SmartCardController_fromSCtoD__InterfaceDevice_fromSCtoD;
extern syncchannel __SmartCardController_data_Ready_SC__InterfaceDevice_dataReady;
extern syncchannel __SmartCardController_start_Application__Application_startApplication;
extern syncchannel __TCPIP_set__mainTimer__Timer__mainTimer__TCPIP_set;
extern syncchannel __TCPIP_reset__mainTimer__Timer__mainTimer__TCPIP_reset;
extern syncchannel __TCPIP_expire__mainTimer__Timer__mainTimer__TCPIP_expire;
extern syncchannel __TCPPacketManager_set__timerP__Timer__timerP__TCPPacketManager_set;
extern syncchannel __TCPPacketManager_reset__timerP__Timer__timerP__TCPPacketManager_reset;
extern syncchannel __TCPPacketManager_expire__timerP__Timer__timerP__TCPPacketManager_expire;
/* Asynchronous channels */
extern asyncchannel __TCPIP_receiveTCP__Application_receiveTCP;
extern asyncchannel __TCPPacketManager_storePacket__TCPPacketManager_retrieve;
#endif
