
#if defined(DEPLOY_RAM0_NAME)
	DEPLOY_RAM0_NAME (RWAL) : ORIGIN = DEPLOY_RAM0_ADDR, LENGTH = DEPLOY_RAM0_SIZE
#endif
#if defined(CACHED_RAM0_NAME)
	CACHED_RAM0_NAME (RWAL) : ORIGIN = CACHED_RAM0_ADDR, LENGTH = CACHED_RAM0_SIZE
#endif
