
/**
 ** MARKER_BEGIN
 ** Auto-generated file, dont modify directly
 ** your changes will be lost !
 **
 ** Generated by DSX on 2010-02-02 15:36:22.885490
 ** by diaxen@ganymede
 ** MARKER_END
 **/

#include "srl.h"
#include "srl_private_types.h"



void hw_init()
{
}
