
objs = block_io.o demux.o dsx_hw_init.o endianness.o idct.o iqzz.o libu.o lock.o main.o mwmr.o ramdac.o tg.o vld.o jpeg_data.o

ifeq ($(CONFIG_HET_BUILD), defined)
objs += platform-mips+arm.o
endif

