
ifeq ($(CONFIG_DRIVER_LCD), defined)
objs += device_lcd.o
endif

ifeq ($(CONFIG_DRIVER_LCD_PCF8833), defined)
subdirs += pcf8833
endif

ifeq ($(CONFIG_DRIVER_LCD_S1D15G00), defined)
subdirs += s1d15g00
endif
