SOCLIB_CPU=mips32el
MUTEKH_CPU=mips

PATH+=/opt/mutekh/bin
export PATH
	
updategeneratedcode:
	cp generated_src/*.h mutekh/examples/systemcams 
	cp generated_src/*.c mutekh/examples/systemcams
	cp Makefile.soclib mutekh/examples/systemcams/Makefile

compilesystemcams:
	cp generated_topcell/top.cc  soclib/soclib/platform/topcells/systemcams/
	

runscams:
	echo "running SystemC-AMS"
	cd soclib/soclib/platform/topcells/systemcams; make; SOCLIB_GDB=S ./executable
