krml_link = krml -verify -warn-error +9 -drop WasmSupport -tmpdir ./out -fsopt --cache_dir -fsopt ./out -fsopt --cache_checked_modules -o ./out/@func_name@ -no-prefix @module_name@ @func_name@.fst

exec = ./out/@func_name@

all: test
	$(krml_link) main.c && $(exec)
test:
	$(krml_link) test.c && $(exec) || (echo "@func_name@ func is not implemented" && exit 1)