/* Generated By:JavaCC: Do not edit this line. TMLExprParserTreeConstants.java Version 5.0 */
package compiler.tmlgrammar;

public interface TMLExprParserTreeConstants
{
  int JJTROOT = 0;
  int JJTEXPRESSION = 1;
  int JJTNAT_ASSIGN = 2;
  int JJTNATEXTENDEDEXPRESSION = 3;
  int JJTNAT_ID = 4;
  int JJTQUEUE_NAT_ID = 5;
  int JJTBOOL_ID = 6;
  int JJTNATFUNCTION2 = 7;
  int JJTNAT_FUNC = 8;
  int JJTNAT_QUEUE_NAT_FUNC = 9;
  int JJTNATOPERATOREXTENDEDEXPRESSION = 10;
  int JJTNAT_OP = 11;
  int JJTQUEUENATEXTENDEDEXPRESSION = 12;
  int JJTQUEUE_NAT_FUNC = 13;
  int JJTBOOLEXTENDEDEXPRESSION = 14;
  int JJTBOOLOPERATOREXTENDEDEXPRESSION = 15;
  int JJTBOOLFUNCTION1 = 16;
  int JJTBOOL_FUNC = 17;
  int JJTBOOL_QUEUE_NAT_FUNC = 18;
  int JJTID = 19;
  int JJTLPAREN = 20;
  int JJTRPAREN = 21;
  int JJTBOOL_OP = 22;
  int JJTNAT_COMP = 23;
  int JJTBOOLNAT_COMP = 24;
  int JJTACTIONGATE = 25;
  int JJTACTIONGATE2 = 26;
  int JJTACTIONGATEVALUE = 27;
  int JJTACTIONGATEVALUE2 = 28;
  int JJTACTIONGATEVALUE3 = 29;
  int JJTTYPE = 30;
  int JJTNAT_VALUE = 31;
  int JJTLITERAL = 32;
  int JJTQUEUENATLITERAL = 33;
  int JJTBOOLEANLITERAL = 34;


  String[] jjtNodeName = {
    "Root",
    "Expression",
    "NAT_ASSIGN",
    "NatExtendedExpression",
    "NAT_ID",
    "QUEUE_NAT_ID",
    "BOOL_ID",
    "NatFunction2",
    "NAT_FUNC",
    "NAT_QUEUE_NAT_FUNC",
    "NatOperatorExtendedExpression",
    "NAT_OP",
    "QueueNatExtendedExpression",
    "QUEUE_NAT_FUNC",
    "BoolExtendedExpression",
    "BoolOperatorExtendedExpression",
    "BoolFunction1",
    "BOOL_FUNC",
    "BOOL_QUEUE_NAT_FUNC",
    "ID",
    "LPAREN",
    "RPAREN",
    "BOOL_OP",
    "NAT_COMP",
    "BOOLNAT_COMP",
    "ActionGate",
    "ActionGate2",
    "ActionGateValue",
    "ActionGateValue2",
    "ActionGateValue3",
    "TYPE",
    "NAT_VALUE",
    "Literal",
    "QueueNatLiteral",
    "BooleanLiteral",
  };
}
/* JavaCC - OriginalChecksum=731d98692e191944b28db12777bdbfd6 (do not edit this line) */
