/* Copyright or (C) or Copr. GET / ENST, Telecom-Paris, Ludovic Apvrille
 * 
 * ludovic.apvrille AT enst.fr
 * 
 * This software is a computer program whose purpose is to allow the
 * edition of TURTLE analysis, design and deployment diagrams, to
 * allow the generation of RT-LOTOS or Java code from this diagram,
 * and at last to allow the analysis of formal validation traces
 * obtained from external tools, e.g. RTL from LAAS-CNRS and CADP
 * from INRIA Rhone-Alpes.
 * 
 * This software is governed by the CeCILL  license under French law and
 * abiding by the rules of distribution of free software.  You can  use,
 * modify and/ or redistribute the software under the terms of the CeCILL
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 * 
 * As a counterpart to the access to the source code and  rights to copy,
 * modify and redistribute granted by the license, users are provided only
 * with a limited warranty  and the software's author,  the holder of the
 * economic rights,  and the successive licensors  have only  limited
 * liability.
 * 
 * In this respect, the user's attention is drawn to the risks associated
 * with loading,  using,  modifying and/or developing or reproducing the
 * software by the user in light of its specific status of free software,
 * that may mean  that it is complicated to manipulate,  and  that  also
 * therefore means  that it is reserved for developers  and  experienced
 * professionals having in-depth computer knowledge. Users are therefore
 * encouraged to load and test the software's suitability as regards their
 * requirements in conditions enabling the security of their systems and/or
 * data to be ensured and,  more generally, to use and operate it in the
 * same conditions as regards security.
 * 
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */





/* Generated By:JavaCC: Do not edit this line. TMLExprParserTreeConstants.java Version 5.0 */
package compiler.tmlgrammar;

public interface TMLExprParserTreeConstants
{
  int JJTROOT = 0;
  int JJTEXPRESSION = 1;
  int JJTNAT_ASSIGN = 2;
  int JJTNATEXTENDEDEXPRESSION = 3;
  int JJTNAT_ID = 4;
  int JJTQUEUE_NAT_ID = 5;
  int JJTBOOL_ID = 6;
  int JJTNATFUNCTION2 = 7;
  int JJTNAT_FUNC = 8;
  int JJTNAT_QUEUE_NAT_FUNC = 9;
  int JJTNATOPERATOREXTENDEDEXPRESSION = 10;
  int JJTNAT_OP = 11;
  int JJTQUEUENATEXTENDEDEXPRESSION = 12;
  int JJTQUEUE_NAT_FUNC = 13;
  int JJTBOOLEXTENDEDEXPRESSION = 14;
  int JJTBOOLOPERATOREXTENDEDEXPRESSION = 15;
  int JJTBOOLFUNCTION1 = 16;
  int JJTBOOL_FUNC = 17;
  int JJTBOOL_QUEUE_NAT_FUNC = 18;
  int JJTID = 19;
  int JJTLPAREN = 20;
  int JJTRPAREN = 21;
  int JJTBOOL_OP = 22;
  int JJTNAT_COMP = 23;
  int JJTBOOLNAT_COMP = 24;
  int JJTACTIONGATE = 25;
  int JJTACTIONGATE2 = 26;
  int JJTACTIONGATEVALUE = 27;
  int JJTACTIONGATEVALUE2 = 28;
  int JJTACTIONGATEVALUE3 = 29;
  int JJTTYPE = 30;
  int JJTNAT_VALUE = 31;
  int JJTLITERAL = 32;
  int JJTQUEUENATLITERAL = 33;
  int JJTBOOLEANLITERAL = 34;


  String[] jjtNodeName = {
    "Root",
    "Expression",
    "NAT_ASSIGN",
    "NatExtendedExpression",
    "NAT_ID",
    "QUEUE_NAT_ID",
    "BOOL_ID",
    "NatFunction2",
    "NAT_FUNC",
    "NAT_QUEUE_NAT_FUNC",
    "NatOperatorExtendedExpression",
    "NAT_OP",
    "QueueNatExtendedExpression",
    "QUEUE_NAT_FUNC",
    "BoolExtendedExpression",
    "BoolOperatorExtendedExpression",
    "BoolFunction1",
    "BOOL_FUNC",
    "BOOL_QUEUE_NAT_FUNC",
    "ID",
    "LPAREN",
    "RPAREN",
    "BOOL_OP",
    "NAT_COMP",
    "BOOLNAT_COMP",
    "ActionGate",
    "ActionGate2",
    "ActionGateValue",
    "ActionGateValue2",
    "ActionGateValue3",
    "TYPE",
    "NAT_VALUE",
    "Literal",
    "QueueNatLiteral",
    "BooleanLiteral",
  };
}
/* JavaCC - OriginalChecksum=731d98692e191944b28db12777bdbfd6 (do not edit this line) */
