
ifeq ($(CONFIG_DRIVER_ENUM_ROOT), defined)
 subdirs += root
endif

ifeq ($(CONFIG_DRIVER_ENUM_PCI), defined)
 subdirs += pci
endif

ifeq ($(CONFIG_DRIVER_ENUM_FDT), defined)
 subdirs += fdt
endif

ifeq ($(CONFIG_DRIVER_ENUM_ISAPNP), defined)
 subdirs += isapnp
endif
