
ifeq ($(CONFIG_DRIVER_ICU_8259), defined)
 subdirs += 8259
endif

ifeq ($(CONFIG_DRIVER_ICU_APIC), defined)
 subdirs += apic
endif

ifeq ($(CONFIG_DRIVER_ICU_SOCLIB), defined)
 subdirs += soclib-icu
endif

ifeq ($(CONFIG_DRIVER_ICU_SOCLIB_XICU), defined)
 subdirs += soclib-xicu
endif

ifeq ($(CONFIG_DRIVER_ICU_MIPS), defined)
 subdirs += mips
endif

ifeq ($(CONFIG_DRIVER_ICU_SPARC), defined)
 subdirs += sparc
endif

ifeq ($(CONFIG_DRIVER_ICU_PPC), defined)
 subdirs += ppc
endif

ifeq ($(CONFIG_DRIVER_ICU_ARM), defined)
 subdirs += arm
endif

ifeq ($(CONFIG_DRIVER_ICU_SAM7), defined)
 subdirs += sam7
endif

ifeq ($(CONFIG_DRIVER_ICU_NIOS2), defined)
 subdirs += nios2
endif

ifeq ($(CONFIG_DRIVER_ICU_LM32), defined)
 subdirs += lm32
endif

ifeq ($(CONFIG_DRIVER_ICU_EMU), defined)
 subdirs += emu
endif
