
DIR_CFLAGS = -D_HEXO_INTTYPES_DEPRECATED

doc_headers = device/block.h device/char.h device/device.h			\
	device/enum.h device/fb.h device/gpio.h device/i2c.h			\
	device/icu.h device/input.h device/lcd.h device/mem.h device/net.h	\
	device/sound.h device/spi.h device/timer.h device/driver.h 

objs = driver.o device.o
subdirs = block char enum fb icu input net sound timer spi lcd gpio i2c mem

